# Generated by Django 4.0.5 on 2022-08-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='link',
            new_name='SocialLink',
        ),
    ]
