# Generated by Django 3.1.4 on 2022-10-29 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221029_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Zone',
        ),
        migrations.AddField(
            model_name='profile',
            name='Zone',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChurchCategory',
        ),
    ]
