# Generated by Django 3.1.4 on 2022-10-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0002_auto_20221030_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
