# Generated by Django 3.1.4 on 2022-11-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0005_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
