# Generated by Django 3.1.4 on 2022-11-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0006_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialmediahandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whatsapp', models.URLField(blank=True, null=True)),
                ('Instagram', models.URLField(blank=True, null=True)),
                ('Facebook', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
